language: node_js

node_js:
  - 4

sudo: false

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: lipwhpJTUMM056Ha6C0+aublNKjNtaRHFXJ5zR7Rmf8y/PPsKeqrarg0zdHt9UEPdLfpHaURKfPn2yT5SC/djSPwVYuTqWlJRKomQpH68w0CU9Tdfc9OjiPXM84eDp3LH+uG4YW3e21gu/dLsxnfHPlFYdmYFvs4OowQW8jieUFvH3cOUjrM67aViCjImxXqAq5q7oIQMUOMXphMLLurFNuH7JnRQtxoMkJpBAxw0nC6Tn8aN+ztLJyLEypbfqOZSbFNMYYa/RB686wNAU+YYQTXz34Tu9ukDmVX8MViHCfI2DLtlqw6ww4xiKiY8BsYijG3mGWIHAvj6oIi2hdcpKUPWT6UQj0cg+4+DlXYmosuBY69eyt9J//KVn/QMljzn3JS8cgTyrSvpYNicSDGt9aXaimKdxwoxNoa20CWvRRC/du6gpfMFRfakRXYZMoxMRtv4eyFZNWB8LUSyBEuuXCU7XCu7+01Ru7D4hhERFvhF/oiqG/Mv1n7XWCVo71V8q/btaip1cCJO25S2rcpN418dZY/MFPjhZ4cDnDyCHRW3y3js8htiiNaXULjoQeUAf1TCyxEPzg8y7RQAX4Ai7Qt3gVPkARbEidEIP4LkwDtZMbCjKz2MkwxRW2jsY03giT6eb5HGoF8byp8er+tMUI3e+jtUYh/o17DyCPl4sw=
    # COVERALLS_REPO_TOKEN
    - secure: gUMX9Rh0SHLb0Ca0Dlfl1rz7ZZRoguOBjKAcQgUDBEbxDGoIXFUleE0wNecQl6e8AEi19cxE11d64XvVbg+k41Jp4Dv16phSJHVLOxsPm3Ncmy39dQ95jO9Xi0SuPJ97RTNGz8odLMhyGDMeq1evJVQHSD955X6SeiIUFxE1D5acFKBRusWGeYeNvzrql3WUndTnGPbLq6SlDzv3qVz2CkSSD2zBgPdQ229kNhBJTEvbYU/luvgbra2w8by89lLgWElM6vWRB7iLte8I4d7XsMTz/+kgikkvLaNmN+iAI1qVzFkH1FIPQNOIqgi0ev2DDo8mFcHOMlxDejpthVHs8cArMWyvbFu6xJmEyeNbFzwjwfoUqWDjQXDF3SCEkHagCQI4zxt4ivZML6jn2K3eIF/KT8DwJ1d4uOFpxVapo+kiddt9LJ7mR+8qmx/DlOMek3oIgNOYHei8HqRVjyDKdxsW3akPydRCSdn20l7Wa967D0W8r19ALPFZmXQrDPThd8VhA30pRFFyu/S0eZlv8aqk+gYGRKIZnsAuc+5Yd9KFLqKFKlTQbE663fwS+sguDlnbs4PE5vAJoXGrlrXtlayJ8905I+B0geZTcvGXAiXUGpVqgJ9l8+7CmzkqDauFEvErRZF8QqSP036grrYsT5ZQERt5ghYxOJokjuKmWAE=

cache:
  directories:
    - node_modules

before_install:
  - npm install --global npm@^3.5.3
  - npm install --global eslint@^1.10.3 jscs@^2.8.0 write-good@^0.9.1 nsp@^2.2.0
  - npm install --global karma-cli@^0.1.2

before_script:
  - npm install karma-firefox-launcher@^0.1.7 karma-phantomjs-launcher@^0.2.2 phantomjs@^1.9.19
  - export KARMA_BROWSERS=Firefox,PhantomJS
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm install codeclimate-test-reporter@^0.3.0 coveralls@^2.11.6
  - KARMA_COVERAGE=lcovonly KARMA_BROWSERS=Firefox karma start ./test/karma.conf.js --single-run
  - cat ./coverage/*/lcov.info | ./node_modules/.bin/codeclimate-test-reporter
  - cat ./coverage/*/lcov.info | ./node_modules/.bin/coveralls

deploy:
  - provider: npm
    email: rs@ruslansagitov.name
    api_key:
      secure: sXXN88Yg7xllAsM1dWauG57nFlrbSA28FQU2rBJF+bMAN4bj7M4n7O6rRgISu7PZ6Nz1nPPEg8/bECNgYwdF/G7NZX4tgo+ERt9wQGYyhN6ebJL6TNtfyh803o/aK9XJFUirdctzsVkMS1ItwBG7v27ocEx6APgrvCWXxoH21OSsBMORJEGznugHYIZ8ucBI59i2+huoc8usxD89zkuCt8+VSNHHNpSFVuV4/RwSb5rkDGd12u1r2svnH5crUO36BdWwtNjznk0H+E0hCLTo0K6Ye5wk3FDmIO9adxgsLsOQAOaqsMf3i8V/zYUjg9w0MuCN0WWBj/BB2kWTNdQZecjRBIC20DOXAF006gnaPtL5B2DfVYvYssarGu1/Li3mgH3gRyE6NNuXEHQxMhswa3xaSGqDjsluV+k24U9M1KUqgkoPHfSWj0Y8Hpn6FbXP9gXqxHt9a4FagAOc0JQa3YwyMR2I5gJ7NF/jLhSAyxDV7Cv1utdMc2LHmMq1pyF7BMySb7eU9mMByyVtRWRhFbECLXUhA2maFWU+0VNREBGlzOX7uZ0QXETPImvv4p6rvZ2pgwhzrNiVKlK4FJZ+XZ/W7ZYHqOs7+dZTlUJ7VrOQcGoZvj74+pcZ1i29eSGzwl4nJm1ItG7eM7vSHzJOHb7grEfgRXqzH+JvyZn7cOU=
    on:
      all_branches: true
      tags: true
      repo: ruslansagitov/jasmine-loud
